spring:
  application:
    name: demo-backend
  datasource:
    name: demo_mysql_db
    platform: mysql
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com/heroku_a42b971124ca32e?reconnect=true
    username: b14713d38c031c
    password: e4df16a0a5ca7ca
    #    url: jdbc:mysql://localhost:3306/demo_backend
    #    username: root
    #    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000

