spring:
  application:
    name: demo-backend
  datasource:
    name: demo_mysql_db
    platform: mysql
    url: jdbc:mysql://localhost:3306/demo_backend
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connectionTestQuery: select 1
      maximum-pool-size: 2
      connection-timeout: 60000

#    url: jdbc:mysql://b14713d38c031c:8f2ee113@us-cdbr-east-03.cleardb.com/heroku_a42b971124ca32e?reconnect=true
#    username: b14713d38c031c
#    password: 8f2ee113