POST http://localhost:8080/v1/contact
Content-Type: application/json

{
 "firstName" :  "Maria",
 "firstSurname" : "Gomez"
}

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "fullName" :  "Fulano"
}


###
GET http://localhost:8080/student